" Name:         High Contrast
" Description:  High contrast theme based on VS Code Default High Contrast
" Author:       Nelson Yeung <nelsyeung@gmail.com>
" Maintainer:   Nelson Yeung <nelsyeung@gmail.com>
" Website:      https://github.com/nelsyeung/high-contrast-theme
" License:      MIT
" Last Updated: Wed  9 Dec 21:41:08 2020

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'high_contrast'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Label Statement
hi! link Macro PreProc
hi! link Operator Normal
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef StorageClass
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#f44747', '#7ca668', '#e2c596',
        \ '#569cd6', '#ffb1fe', '#4ec9b0', '#ffffff', '#080808', '#ce9178',
        \ '#b5cea8', '#dcdcaa', '#a4defb', '#c586c0', '#7acae3', '#b0b0b0']
  if has('nvim')
    let g:terminal_color_0 = '#000000'
    let g:terminal_color_1 = '#f44747'
    let g:terminal_color_2 = '#7ca668'
    let g:terminal_color_3 = '#e2c596'
    let g:terminal_color_4 = '#569cd6'
    let g:terminal_color_5 = '#ffb1fe'
    let g:terminal_color_6 = '#4ec9b0'
    let g:terminal_color_7 = '#ffffff'
    let g:terminal_color_8 = '#080808'
    let g:terminal_color_9 = '#ce9178'
    let g:terminal_color_10 = '#b5cea8'
    let g:terminal_color_11 = '#dcdcaa'
    let g:terminal_color_12 = '#a4defb'
    let g:terminal_color_13 = '#c586c0'
    let g:terminal_color_14 = '#7acae3'
    let g:terminal_color_15 = '#b0b0b0'
  endif
  if get(g:, 'high_contrast_transp_bg', 0)
    hi Normal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal guifg=fg guibg=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#ffffff guibg=NONE gui=bold cterm=bold
    hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  else " opaque
    hi Normal guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#080808 gui=NONE cterm=NONE
    hi Terminal guifg=fg guibg=#000000 gui=NONE cterm=NONE
    hi ToolbarButton guifg=#ffffff guibg=#000000 gui=bold cterm=bold
    hi ToolbarLine guifg=NONE guibg=#000000 gui=NONE cterm=NONE
  endif
  hi Cursor guifg=#b0b0b0 guibg=#569cd6 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffffff guibg=NONE gui=bold cterm=bold
  hi DiffAdd guifg=#7ca668 guibg=#000000 guisp=#7ca668 gui=NONE cterm=NONE
  hi DiffChange guifg=#e2c596 guibg=#000000 guisp=#e2c596 gui=NONE cterm=NONE
  hi DiffDelete guifg=#f44747 guibg=#000000 gui=bold cterm=bold
  hi DiffText guifg=#569cd6 guibg=#000000 guisp=#569cd6 gui=NONE cterm=NONE
  hi NonText guifg=#dcdcaa guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#dcdcaa guibg=#000000 gui=bold cterm=bold
  hi SpellBad guifg=#c586c0 guibg=NONE guisp=#c586c0 gui=undercurl cterm=underline
  hi SpellCap guifg=#c586c0 guibg=NONE guisp=#c586c0 gui=undercurl cterm=underline
  hi SpellLocal guifg=#e2c596 guibg=NONE guisp=#e2c596 gui=undercurl cterm=underline
  hi SpellRare guifg=#4ec9b0 guibg=NONE guisp=#4ec9b0 gui=undercurl cterm=underline
  hi StatusLine guifg=#000000 guibg=#ffffff gui=reverse cterm=reverse
  hi StatusLineNC guifg=#000000 guibg=#7acae3 gui=reverse cterm=reverse
  hi TabLineSel guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi Title guifg=#ce9178 guibg=NONE gui=bold cterm=bold
  hi ColorColumn guifg=NONE guibg=#080808 gui=NONE cterm=NONE
  hi Comment guifg=#7ca668 guibg=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#7ca668 guibg=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#ce9178 guibg=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#080808 gui=NONE cterm=NONE
  hi Function guifg=#dcdcaa guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi Delimiter guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi Directory guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error guifg=#f44747 guibg=#ffffff gui=reverse cterm=reverse
  hi ErrorMsg guifg=#f44747 guibg=#ffffff gui=reverse cterm=reverse
  hi FoldColumn guifg=#b0b0b0 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#b0b0b0 guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch guifg=#ce9178 guibg=NONE gui=standout cterm=standout
  hi Include guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#ffb1fe guibg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#b0b0b0 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#b0b0b0 guibg=#000000 gui=bold cterm=bold
  hi ModeMsg guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#a4defb guibg=#000000 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#000000 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffffff guibg=#b5cea8 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#b5cea8 gui=NONE cterm=NONE
  hi PreProc guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#4ec9b0 guibg=NONE gui=bold cterm=bold
  hi Search guifg=#e2c596 guibg=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#a4defb guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#ce9178 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ffb1fe guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#b5cea8 guibg=#000000 gui=NONE cterm=NONE
  hi TabLineFill guifg=#b5cea8 guibg=#000000 gui=NONE cterm=NONE
  hi Todo guifg=#ffb1fe guibg=NONE gui=bold cterm=bold
  hi Type guifg=#4ec9b0 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#c586c0 guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#7acae3 guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=#ffffff guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#000000 gui=reverse cterm=reverse
  hi WarningMsg guifg=#ce9178 guibg=NONE gui=bold cterm=bold
  hi WildMenu guifg=#dcdcaa guibg=#ffffff gui=reverse cterm=reverse
  hi NormalMode guifg=#000000 guibg=#ffffff gui=reverse cterm=reverse
  hi InsertMode guifg=#000000 guibg=#4ec9b0 gui=bold,reverse cterm=bold,reverse
  hi ReplaceMode guifg=#000000 guibg=#ce9178 gui=bold,reverse cterm=bold,reverse
  hi VisualMode guifg=#000000 guibg=#ffb1fe gui=bold,reverse cterm=bold,reverse
  hi CommandMode guifg=#000000 guibg=#ffb1fe gui=bold,reverse cterm=bold,reverse
  hi! link vimVar Identifier
  hi! link vimFunc Function
  hi! link vimUserFunc Function
  hi! link helpSpecial Special
  hi! link vimSet Normal
  hi! link vimSetEqual Normal
  hi! link vimNotFunc vimCommand
  hi! link vimCommand Statement
  hi vimCommentString guifg=#c586c0 guibg=NONE gui=NONE cterm=NONE
  hi vimCmdSep guifg=#569cd6 guibg=NONE gui=bold cterm=bold
  hi helpExample guifg=#7acae3 guibg=NONE gui=NONE cterm=NONE
  hi helpOption guifg=#4ec9b0 guibg=NONE gui=NONE cterm=NONE
  hi helpNote guifg=#ffb1fe guibg=NONE gui=NONE cterm=NONE
  hi helpVim guifg=#ffb1fe guibg=NONE gui=NONE cterm=NONE
  hi helpHyperTextJump guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi helpHyperTextEntry guifg=#7ca668 guibg=NONE gui=NONE cterm=NONE
  hi vimIsCommand guifg=#dcdcaa guibg=NONE gui=NONE cterm=NONE
  hi vimSynMtchOpt guifg=#e2c596 guibg=NONE gui=NONE cterm=NONE
  hi vimOption guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi vimSynType guifg=#4ec9b0 guibg=NONE gui=NONE cterm=NONE
  hi vimHiLink guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi vimHiGroup guifg=#569cd6 guibg=NONE gui=NONE cterm=NONE
  hi vimGroup guifg=#569cd6 guibg=NONE gui=bold cterm=bold
  hi! link diffAdded Statement
  hi! link diffLine Identifier
  hi gitcommitComment guifg=#7acae3 guibg=NONE gui=italic cterm=italic
  hi! link gitcommitUntracked gitcommitComment
  hi! link gitcommitDiscarded gitcommitComment
  hi! link gitcommitSelected gitcommitComment
  hi gitcommitUnmerged guifg=#b5cea8 guibg=NONE gui=bold cterm=bold
  hi gitcommitOnBranch guifg=#7ca668 guibg=NONE gui=bold cterm=bold
  hi gitcommitBranch guifg=#ffb1fe guibg=NONE gui=bold cterm=bold
  hi! link gitcommitNoBranch gitcommitBranch
  hi gitcommitdiscardedtype guifg=#f44747 guibg=NONE gui=NONE cterm=NONE
  hi gitcommitselectedtype guifg=#b5cea8 guibg=NONE gui=NONE cterm=NONE
  hi gitcommitHeader guifg=#7ca668 guibg=NONE gui=NONE cterm=NONE
  hi gitcommitUntrackedFile guifg=#4ec9b0 guibg=NONE gui=bold cterm=bold
  hi gitcommitDiscardedFile guifg=#f44747 guibg=NONE gui=bold cterm=bold
  hi gitcommitSelectedFile guifg=#b5cea8 guibg=NONE gui=bold cterm=bold
  hi gitcommitUnmergedFile guifg=#dcdcaa guibg=NONE gui=bold cterm=bold
  hi gitcommitFile guifg=#a4defb guibg=NONE gui=bold cterm=bold
  hi! link gitcommitDiscardedArrow gitcommitDiscardedFile
  hi! link gitcommitSelectedArrow gitcommitSelectedFile
  hi! link gitcommitUnmergedArrow gitcommitUnmergedFile
  hi! link shAlias shVariable
  hi! link shCmdSubRegion String
  hi! link shLoop Statement
  hi! link shNoQuote Normal
  hi! link shNumber Normal
  hi! link shOption Normal
  hi! link shQuote String
  hi! link shSetList shVariable
  hi! link shStatement Function
  hi! link shTestOpr Normal
  hi! link shVarAssign shVariable
  hi! link shVariable Normal
  hi shDerefSimple guifg=#a4defb guibg=NONE gui=NONE cterm=NONE
  hi shForPP guifg=#ce9178 guibg=NONE gui=NONE cterm=NONE
  hi shTestPattern guifg=#b5cea8 guibg=NONE gui=NONE cterm=NONE
  hi htmlTag guifg=#b5cea8 guibg=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#b5cea8 guibg=NONE gui=NONE cterm=NONE
  hi htmlTagN guifg=#7acae3 guibg=NONE gui=bold cterm=bold
  hi htmlTagName guifg=#569cd6 guibg=NONE gui=bold cterm=bold
  hi htmlSpecialTagName guifg=#569cd6 guibg=NONE gui=italic cterm=italic
  hi htmlArg guifg=#dcdcaa guibg=NONE gui=NONE cterm=NONE
  hi javaScript guifg=#e2c596 guibg=NONE gui=NONE cterm=NONE
  hi! link jsFuncCall Function
  hi ALEErrorSign guifg=#f44747 guibg=NONE gui=bold cterm=bold
  hi ALEInfoSign guifg=#4ec9b0 guibg=NONE gui=bold cterm=bold
  hi ALEWarningSign guifg=#e2c596 guibg=NONE gui=bold cterm=bold
  hi ALEErrorSignLineNr guifg=#f44747 guibg=NONE gui=NONE cterm=NONE
  hi ALEInfoSignLineNr guifg=#4ec9b0 guibg=NONE gui=NONE cterm=NONE
  hi ALEWarningSignLineNr guifg=#e2c596 guibg=NONE gui=NONE cterm=NONE
  hi ALEError guifg=#f44747 guibg=NONE guisp=#f44747 gui=undercurl cterm=undercurl
  hi ALEErrorLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfo guifg=#4ec9b0 guibg=NONE guisp=#4ec9b0 gui=undercurl cterm=undercurl
  hi ALEInfoLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarning guifg=#e2c596 guibg=NONE guisp=#e2c596 gui=undercurl cterm=undercurl
  hi ALEWarningLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi! link ALEStyleError ALEError
  hi! link ALEStyleErrorSign ALEErrorSign
  hi! link ALEStyleErrorSignLineNr ALEErrorSignLineNr
  hi! link ALEStyleWarning ALEWarning
  hi! link ALEStyleWarningSign ALEWarningSign
  hi! link ALEStyleWarningSignLineNr ALEWarningSignLineNr
  hi! link dartCoreType StorageClass
  if !s:italics
    hi gitcommitComment gui=NONE cterm=NONE
    hi htmlSpecialTagName gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#080808 guibg=#b5cea8 gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'high_contrast_transp_bg', 0)
    hi Normal ctermfg=231 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=231 ctermbg=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  else " opaque
    hi Normal ctermfg=231 ctermbg=16 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi CursorLine ctermfg=NONE ctermbg=232 cterm=NONE
    hi Terminal ctermfg=fg ctermbg=16 cterm=NONE
    hi ToolbarButton ctermfg=231 ctermbg=16 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=16 cterm=NONE
  endif
  hi Cursor ctermfg=145 ctermbg=39 cterm=NONE
  hi CursorLineNr ctermfg=231 ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=107 ctermbg=16 cterm=NONE
  hi DiffChange ctermfg=223 ctermbg=16 cterm=NONE
  hi DiffDelete ctermfg=203 ctermbg=16 cterm=bold
  hi DiffText ctermfg=39 ctermbg=16 cterm=NONE
  hi NonText ctermfg=187 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=187 ctermbg=16 cterm=bold
  hi SpellBad ctermfg=176 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=176 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=223 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=43 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=16 ctermbg=231 cterm=reverse
  hi StatusLineNC ctermfg=16 ctermbg=81 cterm=reverse
  hi TabLineSel ctermfg=231 ctermbg=16 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi ColorColumn ctermfg=NONE ctermbg=232 cterm=NONE
  hi Comment ctermfg=107 ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=39 ctermbg=NONE cterm=NONE
  hi Number ctermfg=107 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=39 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=232 cterm=NONE
  hi Function ctermfg=187 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi Delimiter ctermfg=231 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=39 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=231 cterm=reverse
  hi ErrorMsg ctermfg=203 ctermbg=231 cterm=reverse
  hi FoldColumn ctermfg=145 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=145 ctermbg=NONE cterm=bold
  hi Identifier ctermfg=231 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=173 ctermbg=NONE cterm=standout
  hi Include ctermfg=39 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=219 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=145 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=145 ctermbg=16 cterm=bold
  hi ModeMsg ctermfg=39 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=39 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=117 ctermbg=16 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=16 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=151 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=151 cterm=NONE
  hi PreProc ctermfg=39 ctermbg=NONE cterm=NONE
  hi Question ctermfg=43 ctermbg=NONE cterm=bold
  hi Search ctermfg=223 ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=117 ctermbg=NONE cterm=NONE
  hi Special ctermfg=173 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=219 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=39 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=151 ctermbg=16 cterm=NONE
  hi TabLineFill ctermfg=151 ctermbg=16 cterm=NONE
  hi Todo ctermfg=219 ctermbg=NONE cterm=bold
  hi Type ctermfg=43 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=176 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=81 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=231 ctermbg=16 cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=16 cterm=reverse
  hi WarningMsg ctermfg=173 ctermbg=NONE cterm=bold
  hi WildMenu ctermfg=187 ctermbg=231 cterm=reverse
  hi NormalMode ctermfg=16 ctermbg=231 cterm=reverse
  hi InsertMode ctermfg=16 ctermbg=43 cterm=bold,reverse
  hi ReplaceMode ctermfg=16 ctermbg=173 cterm=bold,reverse
  hi VisualMode ctermfg=16 ctermbg=219 cterm=bold,reverse
  hi CommandMode ctermfg=16 ctermbg=219 cterm=bold,reverse
  hi! link vimVar Identifier
  hi! link vimFunc Function
  hi! link vimUserFunc Function
  hi! link helpSpecial Special
  hi! link vimSet Normal
  hi! link vimSetEqual Normal
  hi! link vimNotFunc vimCommand
  hi! link vimCommand Statement
  hi vimCommentString ctermfg=176 ctermbg=NONE cterm=NONE
  hi vimCmdSep ctermfg=39 ctermbg=NONE cterm=bold
  hi helpExample ctermfg=81 ctermbg=NONE cterm=NONE
  hi helpOption ctermfg=43 ctermbg=NONE cterm=NONE
  hi helpNote ctermfg=219 ctermbg=NONE cterm=NONE
  hi helpVim ctermfg=219 ctermbg=NONE cterm=NONE
  hi helpHyperTextJump ctermfg=39 ctermbg=NONE cterm=NONE
  hi helpHyperTextEntry ctermfg=107 ctermbg=NONE cterm=NONE
  hi vimIsCommand ctermfg=187 ctermbg=NONE cterm=NONE
  hi vimSynMtchOpt ctermfg=223 ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=231 ctermbg=NONE cterm=NONE
  hi vimSynType ctermfg=43 ctermbg=NONE cterm=NONE
  hi vimHiLink ctermfg=39 ctermbg=NONE cterm=NONE
  hi vimHiGroup ctermfg=39 ctermbg=NONE cterm=NONE
  hi vimGroup ctermfg=39 ctermbg=NONE cterm=bold
  hi! link diffAdded Statement
  hi! link diffLine Identifier
  hi gitcommitComment ctermfg=81 ctermbg=NONE cterm=italic
  hi! link gitcommitUntracked gitcommitComment
  hi! link gitcommitDiscarded gitcommitComment
  hi! link gitcommitSelected gitcommitComment
  hi gitcommitUnmerged ctermfg=151 ctermbg=NONE cterm=bold
  hi gitcommitOnBranch ctermfg=107 ctermbg=NONE cterm=bold
  hi gitcommitBranch ctermfg=219 ctermbg=NONE cterm=bold
  hi! link gitcommitNoBranch gitcommitBranch
  hi gitcommitdiscardedtype ctermfg=203 ctermbg=NONE cterm=NONE
  hi gitcommitselectedtype ctermfg=151 ctermbg=NONE cterm=NONE
  hi gitcommitHeader ctermfg=107 ctermbg=NONE cterm=NONE
  hi gitcommitUntrackedFile ctermfg=43 ctermbg=NONE cterm=bold
  hi gitcommitDiscardedFile ctermfg=203 ctermbg=NONE cterm=bold
  hi gitcommitSelectedFile ctermfg=151 ctermbg=NONE cterm=bold
  hi gitcommitUnmergedFile ctermfg=187 ctermbg=NONE cterm=bold
  hi gitcommitFile ctermfg=117 ctermbg=NONE cterm=bold
  hi! link gitcommitDiscardedArrow gitcommitDiscardedFile
  hi! link gitcommitSelectedArrow gitcommitSelectedFile
  hi! link gitcommitUnmergedArrow gitcommitUnmergedFile
  hi! link shAlias shVariable
  hi! link shCmdSubRegion String
  hi! link shLoop Statement
  hi! link shNoQuote Normal
  hi! link shNumber Normal
  hi! link shOption Normal
  hi! link shQuote String
  hi! link shSetList shVariable
  hi! link shStatement Function
  hi! link shTestOpr Normal
  hi! link shVarAssign shVariable
  hi! link shVariable Normal
  hi shDerefSimple ctermfg=117 ctermbg=NONE cterm=NONE
  hi shForPP ctermfg=173 ctermbg=NONE cterm=NONE
  hi shTestPattern ctermfg=151 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=151 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=151 ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=81 ctermbg=NONE cterm=bold
  hi htmlTagName ctermfg=39 ctermbg=NONE cterm=bold
  hi htmlSpecialTagName ctermfg=39 ctermbg=NONE cterm=italic
  hi htmlArg ctermfg=187 ctermbg=NONE cterm=NONE
  hi javaScript ctermfg=223 ctermbg=NONE cterm=NONE
  hi! link jsFuncCall Function
  hi ALEErrorSign ctermfg=203 ctermbg=NONE cterm=bold
  hi ALEInfoSign ctermfg=43 ctermbg=NONE cterm=bold
  hi ALEWarningSign ctermfg=223 ctermbg=NONE cterm=bold
  hi ALEErrorSignLineNr ctermfg=203 ctermbg=NONE cterm=NONE
  hi ALEInfoSignLineNr ctermfg=43 ctermbg=NONE cterm=NONE
  hi ALEWarningSignLineNr ctermfg=223 ctermbg=NONE cterm=NONE
  hi ALEError ctermfg=203 ctermbg=NONE cterm=undercurl
  hi ALEErrorLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfo ctermfg=43 ctermbg=NONE cterm=undercurl
  hi ALEInfoLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarning ctermfg=223 ctermbg=NONE cterm=undercurl
  hi ALEWarningLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi! link ALEStyleError ALEError
  hi! link ALEStyleErrorSign ALEErrorSign
  hi! link ALEStyleErrorSignLineNr ALEErrorSignLineNr
  hi! link ALEStyleWarning ALEWarning
  hi! link ALEStyleWarningSign ALEWarningSign
  hi! link ALEStyleWarningSignLineNr ALEWarningSignLineNr
  hi! link dartCoreType StorageClass
  if !s:italics
    hi gitcommitComment cterm=NONE
    hi htmlSpecialTagName cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=232 ctermbg=151 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  if get(g:, 'high_contrast_transp_bg', 0)
    hi Normal ctermfg=Gray ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=Gray ctermbg=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  else " opaque
    hi Normal ctermfg=Gray ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi Terminal ctermfg=fg ctermbg=Black cterm=NONE
    hi ToolbarButton ctermfg=Gray ctermbg=Black cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  endif
  hi Cursor ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi CursorLineNr ctermfg=Gray ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=DarkRed ctermbg=Black cterm=bold
  hi DiffText ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi NonText ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Yellow ctermbg=Black cterm=bold
  hi SpellBad ctermfg=Magenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=Magenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkYellow ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkCyan ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=Black ctermbg=Gray cterm=reverse
  hi StatusLineNC ctermfg=Black ctermbg=Cyan cterm=reverse
  hi TabLineSel ctermfg=Gray ctermbg=Black cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=bold
  hi ColorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi Comment ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Number ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Red ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi Function ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi Delimiter ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Directory ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi ErrorMsg ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi FoldColumn ctermfg=White ctermbg=NONE cterm=NONE
  hi Folded ctermfg=White ctermbg=NONE cterm=bold
  hi Identifier ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Red ctermbg=NONE cterm=standout
  hi Include ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=White ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=White ctermbg=Black cterm=bold
  hi ModeMsg ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Blue ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Gray ctermbg=Green cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Green cterm=NONE
  hi PreProc ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Question ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi Search ctermfg=DarkYellow ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Special ctermfg=Red ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=Green ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=Green ctermbg=Black cterm=NONE
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Visual ctermfg=Gray ctermbg=Black cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=Black cterm=reverse
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WildMenu ctermfg=Yellow ctermbg=Gray cterm=reverse
  hi NormalMode ctermfg=Black ctermbg=Gray cterm=reverse
  hi InsertMode ctermfg=Black ctermbg=DarkCyan cterm=bold,reverse
  hi ReplaceMode ctermfg=Black ctermbg=Red cterm=bold,reverse
  hi VisualMode ctermfg=Black ctermbg=DarkMagenta cterm=bold,reverse
  hi CommandMode ctermfg=Black ctermbg=DarkMagenta cterm=bold,reverse
  hi! link vimVar Identifier
  hi! link vimFunc Function
  hi! link vimUserFunc Function
  hi! link helpSpecial Special
  hi! link vimSet Normal
  hi! link vimSetEqual Normal
  hi! link vimNotFunc vimCommand
  hi! link vimCommand Statement
  hi vimCommentString ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi vimCmdSep ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi helpExample ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi helpOption ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi helpNote ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi helpVim ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi helpHyperTextJump ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi helpHyperTextEntry ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi vimIsCommand ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi vimSynMtchOpt ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi vimOption ctermfg=Gray ctermbg=NONE cterm=NONE
  hi vimSynType ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi vimHiLink ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi vimHiGroup ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi vimGroup ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi! link diffAdded Statement
  hi! link diffLine Identifier
  hi gitcommitComment ctermfg=Cyan ctermbg=NONE cterm=italic
  hi! link gitcommitUntracked gitcommitComment
  hi! link gitcommitDiscarded gitcommitComment
  hi! link gitcommitSelected gitcommitComment
  hi gitcommitUnmerged ctermfg=Green ctermbg=NONE cterm=bold
  hi gitcommitOnBranch ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi gitcommitBranch ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi! link gitcommitNoBranch gitcommitBranch
  hi gitcommitdiscardedtype ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi gitcommitselectedtype ctermfg=Green ctermbg=NONE cterm=NONE
  hi gitcommitHeader ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi gitcommitUntrackedFile ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi gitcommitDiscardedFile ctermfg=DarkRed ctermbg=NONE cterm=bold
  hi gitcommitSelectedFile ctermfg=Green ctermbg=NONE cterm=bold
  hi gitcommitUnmergedFile ctermfg=Yellow ctermbg=NONE cterm=bold
  hi gitcommitFile ctermfg=Blue ctermbg=NONE cterm=bold
  hi! link gitcommitDiscardedArrow gitcommitDiscardedFile
  hi! link gitcommitSelectedArrow gitcommitSelectedFile
  hi! link gitcommitUnmergedArrow gitcommitUnmergedFile
  hi! link shAlias shVariable
  hi! link shCmdSubRegion String
  hi! link shLoop Statement
  hi! link shNoQuote Normal
  hi! link shNumber Normal
  hi! link shOption Normal
  hi! link shQuote String
  hi! link shSetList shVariable
  hi! link shStatement Function
  hi! link shTestOpr Normal
  hi! link shVarAssign shVariable
  hi! link shVariable Normal
  hi shDerefSimple ctermfg=Blue ctermbg=NONE cterm=NONE
  hi shForPP ctermfg=Red ctermbg=NONE cterm=NONE
  hi shTestPattern ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlTagN ctermfg=Cyan ctermbg=NONE cterm=bold
  hi htmlTagName ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi htmlSpecialTagName ctermfg=DarkBlue ctermbg=NONE cterm=italic
  hi htmlArg ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi javaScript ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi! link jsFuncCall Function
  hi ALEErrorSign ctermfg=DarkRed ctermbg=NONE cterm=bold
  hi ALEInfoSign ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi ALEErrorSignLineNr ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi ALEInfoSignLineNr ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi ALEWarningSignLineNr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi ALEError ctermfg=DarkRed ctermbg=NONE cterm=undercurl
  hi ALEErrorLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEInfo ctermfg=DarkCyan ctermbg=NONE cterm=undercurl
  hi ALEInfoLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ALEWarning ctermfg=DarkYellow ctermbg=NONE cterm=undercurl
  hi ALEWarningLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi! link ALEStyleError ALEError
  hi! link ALEStyleErrorSign ALEErrorSign
  hi! link ALEStyleErrorSignLineNr ALEErrorSignLineNr
  hi! link ALEStyleWarning ALEWarning
  hi! link ALEStyleWarningSign ALEWarningSign
  hi! link ALEStyleWarningSignLineNr ALEWarningSignLineNr
  hi! link dartCoreType StorageClass
  if !s:italics
    hi gitcommitComment cterm=NONE
    hi htmlSpecialTagName cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=DarkGray ctermbg=Green cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Color:  black          #000000  ~        Black
" Color:  red            #f44747  ~        DarkRed
" Color:  green          #7ca668  ~        DarkGreen
" Color:  yellow         #e2c596  ~        DarkYellow
" Color:  blue           #569cd6  ~        DarkBlue
" Color:  magenta        #ffb1fe  ~        DarkMagenta
" Color:  cyan           #4ec9b0  ~        DarkCyan
" Color:  white          #ffffff  ~        Gray
" Color:  brightblack    #080808  ~        DarkGray
" Color:  brightred      #ce9178  ~        Red
" Color:  brightgreen    #b5cea8  ~        Green
" Color:  brightyellow   #dcdcaa  ~        Yellow
" Color:  brightblue     #a4defb  ~        Blue
" Color:  brightmagenta  #c586c0  ~        Magenta
" Color:  brightcyan     #7acae3  ~        Cyan
" Color:  brightwhite    #b0b0b0  ~        White
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: brightblack brightred brightgreen brightyellow
" Term Colors: brightblue brightmagenta brightcyan brightwhite
" Background: dark
" vim: et ts=2 sw=2
